### ISSUE TITLE
Feature: Add CSR feature

### ISSUE THREAD

**Issue by nyagamunene** [absmach/certs#22]
### Is your feature request related to a problem? Please describe.

For now while issuing certs there is no feature for the client to request for certs which is a standard.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

While issuing certs the client can provide a csr file which has the request for the certs.

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
@nyagamunene What's the status of this one?

**Comment by nyagamunene** [comment]
I have been working on this one I will send a draft PR later today
