### ISSUE TITLE
Field is only relevant to prism

### ISSUE THREAD

**Issue by SammyOina** [absmach/certs#6]
https://github.com/absmach/certs/blob/1bea63e77de295ddfa32cd4ec7ad018bad22feea/certs.go#L15

absmach certs should be more generic

**Comment by nyagamunene** [comment]
> https://github.com/absmach/certs/blob/1bea63e77de295ddfa32cd4ec7ad018bad22feea/certs.go#L15
> 
> absmach certs should be more generic

Noted
